dns_code = "eWBRKL3JuN4W6KDj2vLkt94o"

[service]
exec = "./start.sh"
log = false

[sync]
origin = "https://github.com/awtterpip/bmc1"
targets = [ "mods/", "mods_disabled/", "skinpls/", "versions/", "world/", "banned-ips.json", "banned-players.json", "droplet.toml", "ops.json", "options.txt", "server-icon.png", "server.properties", "variables.txt", "whitelist.json" ]